# Generated by Django 5.2.14 on 2026-05-25 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_uploadbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawEmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('source_value', models.FloatField()),
                ('source_unit', models.CharField(max_length=50)),
                ('normalized_value', models.FloatField(blank=True, null=True)),
                ('normalized_unit', models.CharField(default='kgCO2e', max_length=50)),
                ('activity_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FLAGGED', 'FLAGGED'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization')),
                ('upload_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.uploadbatch')),
            ],
        ),
    ]
