# Generated by Django 5.2.14 on 2026-05-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_rawemissionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawemissionrecord',
            name='scope_category',
            field=models.CharField(default='Scope 1', max_length=20),
        ),
    ]
